version: '3'

services:

  kstream:
    build: backend/stream
    container_name: kstream
    restart: always
    ports:
      - 3090:3090
    environment:
      KAFKA_HOST: $KAFKA_HOST
      KAFKA_USER_NAME: $KAFKA_USER_NAME
      KAFKA_PASSWORD: $KAFKA_PASSWORD
      KAFKA_IN_TOPIC: $KAFKA_IN_TOPIC
      KAFKA_OUT_TOPIC: $KAFKA_OUT_TOPIC
      # OWNER: $OWNER
      # KAFKA_HOST: kafka:9092
      # KAFKA_USER_NAME: $KAFKA_USER_NAME
      # KAFKA_PASSWORD: $KAFKA_PASSWORD
      # KAFKA_IN_TOPIC: read
      # KAFKA_OUT_TOPIC: write

      # zookeeper:
      #   image: 'bitnami/zookeeper:latest'
      #   container_name: zookeeper
      #   ports:
      #     - '2181:2181'
      #   environment:
      #     - ALLOW_ANONYMOUS_LOGIN=yes

      # kafka:
      #   image: 'bitnami/kafka:latest'
      #   container_name: kafka
      #   ports:
      #     - '9092:9092'
      #     - '9093:9093'
      #   environment:
      #     - KAFKA_BROKER_ID=1
      #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #     - ALLOW_PLAINTEXT_LISTENER=yes
      #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      #     - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      #   depends_on:
      #     - zookeeper
